# Site settings
title: Ioannis (Yannis) Mitliagkas
email: ioannis@iro.umontreal.ca
#email: imit@stanford.edu
#email: ioannis@utexas.edu
description: > # this means to ignore newlines until "baseurl:"
  Associate Professor, Mila, Computer Science, University of Montreal.
  Machine learning and optimization.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mitliagkas.github.io" # the base hostname & protocol for your site
twitter_username: bouzoukipunks
github_username:  mitliagkas

plugins:
  - jekyll-redirect-from

highlighter: pygments

# Build settings
markdown: kramdown

exclude: [vendor]
