#!/usr/bin/env python3
"""Generate CV material from _data/publications.yml and _data/venues.yml.

  python3 tools/cv.py OUTDIR

writes, into OUTDIR:
  pubs-accepted.tex   \\vbox entries for the long CV (replaces biblio-accepted.tex)
  pubs-workshop.tex   workshop papers
  pubs-preprints.tex  preprints under review and technical reports
  pubsummary.tex      the "Publication summary" sentence for the short CV
  ccv-new.bib         BibTeX of papers not yet marked `ccv: true`, for CCV import
                      (Utilities > Import Publication from file)

In the long CV:  \\input{pubs-accepted}  etc.   In the short CV:  \\input{../pubsummary}
"""
import os, sys, re, yaml
from collections import Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load = lambda n: yaml.safe_load(open(os.path.join(ROOT, "_data", n + ".yml"), encoding="utf-8"))
P, V = load("publications"), load("venues")

TEX = [("é", "\\'e"), ("É", "\\'E"), ("è", "\\`e"), ("á", "\\'a"), ("í", "\\'i"), ("ó", "\\'o"),
       ("ú", "\\'u"), ("ö", '\\"o'), ("ü", '\\"u'), ("ä", '\\"a'), ("ç", "\\c{c}"), ("à", "\\`a"),
       ("ô", "\\^o"), ("–", "--"), ("&", "\\&")]
def tex(s):
    for a, b in TEX: s = s.replace(a, b)
    return s

def author_tex(a):
    a = tex(a)
    star = a.endswith("*"); a = a.rstrip("*")
    a = re.sub(r"\.\s+", ".~", a)
    if "Mitliagkas" in a: a = "\\textbf{" + a + "}"
    return a + ("*" if star else "")

def venue_line(p):
    ax = p.get("arxiv")
    if p["status"] == "accepted" and p.get("venue"):
        v = f"{V[p['venue']]['name']}, {p['year']}"
    elif p["status"] == "workshop":
        v = p["venue_text"] + (f", arXiv preprint arXiv:{ax}" if ax else "")
    elif p.get("venue_text"):
        v = p["venue_text"] + (f", arXiv:{ax}" if ax and "arXiv" not in p["venue_text"] else "")
    else:
        v = f"arXiv preprint arXiv:{ax}" if ax else f"Preprint, {p['year']}"
    if p.get("note"): v += " " + p["note"]
    return v

def entry(p):
    lines = ["\\vbox{", ", ".join(author_tex(a) for a in p["authors"]) + "\\\\",
             "\\newblock {", tex(p["title"]), "} \\\\"]
    if p.get("arxiv") and p["status"] == "accepted":
        lines.append("\\newblock {arXiv:%s} \\\\" % p["arxiv"])
    v = tex(venue_line(p))
    lines.append("\\newblock {\\em {%s}}" % v)
    if p.get("highlight"):
        lines.append("\\ [\\textbf{\\textcolor{red}{%s presentation}}]" % p["highlight"])
    lines += ["\\newline", "}", ""]
    return "\n".join(lines)

def write(path, text):
    open(path, "w", encoding="utf-8").write(text)
    print("wrote", path)

def bibkey(p): return re.sub(r"[^a-z0-9]", "", p["id"])

def bib(p):
    acc = p["status"] == "accepted"
    vt = V[p["venue"]] if acc and p.get("venue") else None
    kind = "article" if vt and vt["type"] == "journal" else "inproceedings"
    f = {"title": "{" + p["title"] + "}", "author": " and ".join(a.rstrip("*") for a in p["authors"]), "year": str(p["year"])}
    if vt: f["journal" if kind == "article" else "booktitle"] = vt["name"]
    else: f["booktitle"] = p.get("venue_text", "")
    if p.get("url"): f["url"] = p["url"]
    elif p.get("arxiv"): f["url"] = "https://arxiv.org/abs/" + p["arxiv"]
    if p.get("arxiv"): f["eprint"] = p["arxiv"]
    body = ",\n".join(f"  {k} = {{{v}}}" for k, v in f.items() if v)
    return f"@{kind}{{{bibkey(p)},\n{body}\n}}\n"

def main(out):
    os.makedirs(out, exist_ok=True)
    hdr = "% GENERATED by tools/cv.py from _data/publications.yml. Edit the data file, not this file.\n"
    for status, name in [("accepted", "pubs-accepted.tex"), ("workshop", "pubs-workshop.tex"), ("preprint", "pubs-preprints.tex")]:
        write(os.path.join(out, name), hdr + "\n".join(entry(p) for p in P if p["status"] == status).rstrip() + "\n")
    acc = [p for p in P if p["status"] == "accepted"]
    c = Counter(p["venue"] for p in acc)
    main_v = [k for k, v in V.items() if v.get("summary")]
    main_v.sort(key=lambda k: -c[k])
    parts = [f"{c[k]} in {V[k]['short']}" for k in main_v if c[k]]
    parts[0] = parts[0].replace(" in ", " published papers in ", 1)
    others = [k for k in c if k not in main_v]
    n_other = sum(c[k] for k in others)
    other_names = ", ".join(V[k]["short"] for k in sorted(others, key=lambda k: -c[k]))
    write(os.path.join(out, "pubsummary.tex"), hdr +
          ", ".join(parts) + ".\n" + f"{n_other} other publications in various venues ({tex(other_names)}).\n")
    new = [p for p in P if p["status"] in ("accepted", "workshop") and not p.get("ccv")]
    write(os.path.join(out, "ccv-new.bib"), "% Papers not yet marked `ccv: true`. Import in CCV: Utilities > Import Publication from file.\n"
          "% After importing, mark student co-authors in CCV, then set `ccv: true` on these entries.\n\n" + "\n".join(bib(p) for p in new))
    print("counts:", ", ".join(f"{V[k]['short']} {c[k]}" for k in sorted(c, key=lambda k: -c[k])))

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "tools", "out"))
